name: Android CI

on: [push]

jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - uses: gradle/gradle-build-action@v3
              with:
                  cache-disabled: true

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Detekt
              shell: bash
              run: ./gradlew detekt

            - name: Publish Checkstyle Report
              uses: Juuxel/publish-checkstyle-report@v1.0.0
              with:
                  reports: '**/build/**/detekt.xml'

