name: Android CI

on: [push]

jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - uses: gradle/gradle-build-action@v3
              with:
                  cache-disabled: true

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Detekt
              shell: bash
              run: ./gradlew detekt

            - name: Publish Checkstyle Report
              uses: Juuxel/publish-checkstyle-report@v1.0.0
              with:
                  reports: '**/build/**/detekt.xml'

    Tests:
        runs-on: ubuntu-latest
        needs: Detekt
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - uses: gradle/gradle-build-action@v3
              with:
                  cache-disabled: true

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run Unit Tests
              run: ./gradlew testDebugUnitTest --stacktrace

    Release_Build:
        runs-on: ubuntu-latest
        needs: Tests
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17

            -   name: Decode Keystore
                run: |
                    echo "${{ secrets.RELEASE_STORE_FILE }}" | base64 --decode > sidspacekeystore.jks
                    ls -la sidspacekeystore.jks

            -   name: Validate Keystore
                run: |
                    keytool -list -v \
                      -keystore sidspacekeystore.jks \
                      -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" \
                      -alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
                      -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}"

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build release APK
                env:
                    RELEASE_STORE_FILE: "${{ github.workspace }}/sidspacekeystore.jks"
                    RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
                    RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
                    RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
                run: ./gradlew assembleRelease --stacktrace

            -   name: Upload release APK
                uses: actions/upload-artifact@v4
                with:
                    name: app-release
                    path: app/build/outputs/apk/release/*.apk
